rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-head

# Bundler is acting up on ruby-head; since we don't currently have any
# dependencies, stub out the install.
#
# bundler_args: --without docs
install:
  - echo "No dependencies."
  - date

notifications:
  email:
    - brwcodes@gmail.com